### ISSUE TITLE
Great work, open for issues?

### ISSUE THREAD

**Issue by Petros626** [atanasko/WOD-3D-Object-Detection#1]
Hey, 

I followed your approach in this comment here: https://github.com/ultralytics/ultralytics/issues/3078. Would it possible for you to answer some question, when I'm implementing YOLOv8 OBB with BEV-images?

With best regards

Petros

**Comment by atanasko** [comment]
@Petros626 sure I'll try

**Comment by Petros626** [comment]
I'll wait for your mail, meanwhile closing this one here.

**Comment by atanasko** [comment]
@Petros626 you can send me mail on atanasko.mitrev@gmail.com
